ROOT_DIR: "./128_100" 
GPU: -1
MODEL_STATE_FILE: "./ckpt"

TRAINING_INFO:
  BATCH_SIZE: 64
  MODEL_TYPE: "CONV" #ou attention 
  LR: 0.00001
  EPOCHS: 50
  MODEL_ARGS:
    hidden_size: 64
    dropout_p: 0.7
    n_layers: 4